name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install gym
        pip install -r requirements.txt

    - name: 3. Ensure env.so is executable
      run: chmod +x env.cpython-38-x86_64-linux-gnu.so

    - name: 4. Download models
      run: |
        curl -L -o model.zip "https://drive.google.com/uc?export=download&id=17FpqB_P3hZu0w6QWY2Pp16FEo2suW2Ss"
        unzip model.zip

    - name: 5. Run Evaluation
      run: python eval.py --token a91aae52cff9ef65932db06b150ffd47
